version: "3.9"

services:

  eureka-service:
    image: eureka-service:1.0
    container_name: eureka-service
    ports:
      - "8761"        # Container port 8761; host port will be dynamically assigned if needed
    networks:
      - micro-net

  api-gateway:
    image: api-gateway:1.0
    container_name: api-gateway
    ports:
      - "8080"        # Container port 8080; host port will be assigned dynamically if default busy
    depends_on:
      - eureka-service
    networks:
      - micro-net

  order-service:
    image: order-service:1.0
    container_name: order-service
    ports:
      - "8081"
    depends_on:
      - eureka-service
    networks:
      - micro-net

  payment-service:
    image: payment-service:1.0
    container_name: payment-service
    ports:
      - "8082"
    depends_on:
      - eureka-service
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
